# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bernhard Hodler
title: Corporate Management, Consulting, Financial Investments
email: bernhard@hodler-consulting.com
#website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: udkcsgo
#github_username:  theudk
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: theudkch
linkedin_username: bernhard-hodler
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/img01.jpeg
about_content: | # this will include new lines to allow paragraphs
  -	**Senior Manager** with strong analytical and communication skills
  - Multiyear **experience at Executive Board, as CEO and at Board of Director** level. I have successfully shaped and implemented strategies for large organizations
  - **Over 30 years of experience in the financial services industry** internationally in Wealth and Asset Management, Private and Investment Banking
  - Bachelor's degree in Business Administration and **MBA from Wharton University**

content:
  - title: About My Services # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Corporate Management and Governance:**

      I take over mandates as member of the Board of Directors, member of Advisory Boards or Foundation Boards. 
      
      **Consulting:**

      I provide consulting services mainly in the financial services industry (Wealth and Asset Management, Private and Investment Banking). 
      
      **Financial Investments and support for start-up companies:**

      I am an active investor in and advisor of start-up companies. The financial investments can be coupled with a mandate as Board of Director or advisor.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      #Ent
      - layout: left
        title: Entrepreneur
        link: hodler-consulting.com
        # link_text: boringcompany.com
        sub_title: Consultant, Multiple Board Member, Investor
        caption: 2020 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Self-employed entrepreneur mainly consulting in the financial services industry and active as an investor and BoD in the start-up space
      #JB
      - layout: left
        title: Julius Baer Group, Zurich
        link: juliusbaer.com
        # link_text: boringcompany.com
        sub_title: Member of the Executive Board, CEO
        caption: 1998 - 2020
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Various functions (CRO, Head Credit, Head Corporate Services, COO, CEO). Managed over 6000 employees as CEO and shaped and implemented strategy
      #CS
      - layout: left
        title: Credit Suisse, London and Zurich
        link: credit-suisse.com
        # link_text: boringcompany.com
        sub_title: Managing Director, Investment Banking
        caption: 1994 - 1998
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Worked 2 years in London and 2 years in Zurich in the investment banking division
      #SBC
      - layout: left
        title: Swiss Bank Corporation, Tokyo and Zurich
        link: "https://en.wikipedia.org/wiki/Swiss_Bank_Corporation"
        link_text: Wikipedia Entry
        sub_title: Executive Director, Investment Banking
        caption: 1990 - 1994
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Worked 2 years in Tokyo and 2 years in Zurich in the investment banking division
      #CSFB
      - layout: left
        title: Credit Suisse First Boston, Zurich
        link: "https://en.wikipedia.org/wiki/Credit_Suisse_First_Boston"
        link_text: Wikipedia Entry
        sub_title: Director, Business Audit
        caption: 1987 - 1990
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Senior Business Auditor in the international division with direct overall audit responsibility for CSFB Germany and CSFB Netherland
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      #Wrtn
      - layout: left
        title: Wharton University, Philadelphia
        caption: 2004
        sub_title: Advanced Management Program (AMP)
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **International Executive MBA** Program focusing on international management and strategy shaping and implementation
      #SFI
      - layout: left
        title: Swiss Finance Institute, Zurich
        caption: 1999 - 2000
        sub_title: Advanced Executive Program (AEP)
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          **Senior Manager Certification in Banking**. Modules: Strategic Bank Management, Corporate Development, Retail-, Private- and Commercial Banking
      #GARP
      - layout: left
        title: Global Association of Risk Professionals
        caption: 1996 - 1997
        sub_title: Financial Risk Manager (FRM Garp)
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Leading Certification for **International Risk Managers**
      #UASB
      - layout: left
        title: University of Applied Sciences, Bern
        caption: 1984 - 1987
        sub_title: Bachelor of Business Administration
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Specializing in **Banking & Finance and Controlling**

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Management, Leadership and the Financial Services Industry some of my other interests and hobbies are:
      - Traveling
      - Reading
      - Classical Music
      - Tennis and Padel-Tennis
      - Biking
      - Skiing


      ![Biking](/images/img03.jpg "Biking"){:height="25%" width="25%"}
      ![Skiing](/images/img02.jpg "Skiing"){:height="25%" width="25%"}

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
